name = "dhealth-redirect"
type = "javascript"
account_id = "e14bc559836e4e1ea4f75ec16d420945"
workers_dev = true
route = "https://dhealth.cflink.io/*"
zone_id = "b0b1d70d09fa1403d12713ed58404544"
kv_namespaces = [
  { binding = "LINKS", id = "4a6889b26e2a443ca870b137fcdf07dc", preview_id = "4a6889b26e2a443ca870b137fcdf07dc" }
]
