name = "dhealth-redirect"
main = "worker.js"
compatibility_date = "2023-02-08"

account_id = "e14bc559836e4e1ea4f75ec16d420945"
workers_dev = true
route = { pattern = "dhealth.cflink.io/*", zone_name = "cflink.io" }


kv_namespaces = [
  { binding = "LINKS", id = "4a6889b26e2a443ca870b137fcdf07dc", preview_id = "4a6889b26e2a443ca870b137fcdf07dc" }
]